### ISSUE TITLE
Check that ranger fits our needs in terms of functionnalities

### ISSUE THREAD

**Issue by TanguySoto** [georgeslabreche/opssat-orbitai#22]
This story is part of epic [Evaluate the ranger library for batch training with Random Forest](https://github.com/georgeslabreche/opssat-orbitai/issues/19).

## Objective
The objective of this story is to determine if:
1. we can save and load models.
2. the loaded models return expected predictions.
~~3. the loaded models can be trained further after being loaded~~ (reduced scope)

~~**Note on Objective 3:** Does RF allow this to begin with regardless of what ranger has implemented and if so can it be done in ranger?~~  (reduced scope)

## Acceptance criteria
- [x] 1. Check that ranger can save and load models, [it seems possible](https://github.com/imbs-hl/ranger/blob/ce497711884c783e133fb36750b60de4c140773f/src/Forest.cpp#L403-L443) but we must first confirm that it is before integrating ranger into OrbitAi. What needs to be done:
  - [x] 1.1. Check that loaded models give the same prediction results as models trained prior to being saved.
  - [x] 1.2. Update README with instructions on how to save and load models.
  - [x] 1.3. Save all model files, input datasets, results summary, and comparison observations in a results folder for record keeping and referencing purposes.
- [x] 2. Check that ranger's inputs format works for OrbitAI's needs (try to feed it PD values and labels from our training.csv files collected in previous runs).

## Verifying the save and load functionalities
1. Prepare two different datasets: `n` training inputs and `m` test inputs. 
2. Train and predict:
  2.1. Start program.
  2.2. Train the model with dataset `n` as inputs.
  2.3. Save the model.
  2.4. Exit program.
  2.5. Start program.
  2.6. Predict the labels with the dataset `m` as inputs.
  2.7. Save the prediction results in a text or csv file.
  2.8. Exit program.
  2.9. Calculate classification matrix.

~~3. Train and predict in multiple sessions with saving and loading.
 3.1. Split training dataset `n` in two: e.g. `n1` and `n2` 
 3.2. Start program.
 3.3. Train model with dataset `n1` as inputs.
 3.4. Save the model.
 3.5. Exit program.
 3.6. Start program.
 3.7. Load the model saved in step 3.4.
 3.8. Predict the labels with the dataset `m` as inputs.
 3.9. Save the prediction results in a text or csv file.
 3.10. Exit Program.
 3.11. Compare prediction results obtained in steps 2.4. with those obtained in steps 3.9. They must be different in order for the rest of the verification procedure to be valid. If they are the same then restart from step 3.1. and make sure that splitting dataset `n` results in a smaller and less diverse sample size for the `n1` training dataset.
 3.12. Start program.
 3.13. Load the model saved in step 3.4.
 3.14. Train model with dataset `n2` as inputs.
 3.15. Save the model.
 3.16. Exit program.
 3.17. Start program.
 3.18. Load the model saved in step 3.15.
 3.19. Predict the labels with the dataset `m` as inputs.
 3.20. Save the prediction results in a text or csv file.
 3.21. Exit program.
4. Verification
  4.1. Compare prediction results obtained in steps 2.4. with those obtained in steps 3.20. They should be exactly the same.
  4.2. Use the Terminal tool `vbindiff` to compare the model saved in step 2.5. with the model saved in 3.4. They should be different.
  4.3. Use the Terminal tool `vbindiff` to compare the model saved in step 2.5. with the model saved in 3.15. They should be the same.~~  (reduced scope)

**Comment by georgeslabreche** [comment]
@Evridiki-ase I noticed that you included the ranger code into the OrbitAI repo. Just an early warning that eventually this will have to be done as a "git submodule" rather than copy and pasting ranger repo files directly to the repo. To prepare for this, I have forked the ranger repo and created an orbitai branch, here: https://github.com/georgeslabreche/ranger

You can choose to do this now or wait until you tackle [this issue](https://github.com/georgeslabreche/opssat-orbitai/issues/37). However, keep in mind that if you wait you will have to redo all the changes you have done and will be doing so that they are instead included in [the forked repo of ranger](https://github.com/georgeslabreche/ranger).

**Comment by georgeslabreche** [comment]
@Evridiki-ase lemme know what you want me to do with the re-assignment.

**Comment by georgeslabreche** [comment]
@Evridiki-ase please don't delete this comment, we need it for record keeping on how to proceed since we can't rely on memory. If there are concerns then it's best to record them as responses to the comment so that we can take them into account moving forward and not suffer from missing information. I've reinstated the original comment here:

@Evridiki-ase lemme know what you want me to do with the re-assignment. Until I get some instructions I'll assume it's for me to review so here are my notes on that aspect with the issue assigned back to you for clarification:

1. In your [README's usage section](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/ranger#usage) I see that you are using the same dataset for training and prediction. This should be two separate datasets as per points 1, 2.2 and 2.3 in the "Verifying the save and load functionalities" section of this issues' description. I don't know if this is something that's only in the README or if you used the same dataset for verifying the save and load functionalities so let's clarify. In the ideal world we we would use [separate datasets for training, validation, and testing](https://stats.stackexchange.com/a/19051) but for the scope of our work and timeline constraints [we can settle with just separate training and testing datasets](https://datascience.stackexchange.com/a/61431).

2. In your README I noticed that you have a training_ranger.csv file in `../training/mochi-2021-04-16_18-28-31/logs/` but no such file was committed to the repo so I cannot go through the instructions. That being said, that training_ranger.csv file should not be located in the `../training/mochi-2021-04-16_18-28-31/logs/` directory. This is because the results folder is an exclusive archive for all experiment result data that we downlinked from the spacecraft and as such it should not be tampered with because it serves both for record keeping and as a reference to work unrelated to the exploration that you're doing with ranger. We should instead organize everything withing a dedicated ranger directory which contains a git submodule folder to the ranger repo, as described [here](https://github.com/georgeslabreche/opssat-orbitai/issues/22#issuecomment-841690311). By way of example, consider the [Mochi folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi) which has the `MochiMochi @ ba8574e` gitsubmodule folder and the [test_data folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi/test_data) with the training and test datasets that we use to analyze the algorithm and models with custom code that we have in the [tools folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi/tools).

**Comment by georgeslabreche** [comment]
@Evridiki-ase please don't delete this comment, we need it for record keeping on how to proceed since we can't rely on memory. If there are concerns then it's best to record them as responses to the comment so that we can take them into account moving forward and not suffer from missing information. I've reinstated the original comment here:

@Evridiki-ase lemme know what you want me to do with the re-assignment. Until I get some instructions I'll assume it's for me to review so here are my notes on that aspect with the issue assigned back to you for clarification:

1. In your [README's usage section](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/ranger#usage) I see that you are using the same dataset for training and prediction. This should be two separate datasets as per points 1, 2.2 and 2.3 in the "Verifying the save and load functionalities" section of this issues' description. I don't know if this is something that's only in the README or if you used the same dataset for verifying the save and load functionalities so let's clarify. In the ideal world we we would use [separate datasets for training, validation, and testing](https://stats.stackexchange.com/a/19051) but for the scope of our work and timeline constraints [we can settle with just separate training and testing datasets](https://datascience.stackexchange.com/a/61431).

2. In your README I noticed that you have a training_ranger.csv file in `../training/mochi-2021-04-16_18-28-31/logs/` but no such file was committed to the repo so I cannot go through the instructions. That being said, that training_ranger.csv file should not be located in the `../training/mochi-2021-04-16_18-28-31/logs/` directory. This is because the results folder is an exclusive archive for all experiment result data that we downlinked from the spacecraft and as such it should not be tampered with because it serves both for record keeping and as a reference to work unrelated to the exploration that you're doing with ranger. We should instead organize everything withing a dedicated ranger directory which contains a git submodule folder to the ranger repo, as described [here](https://github.com/georgeslabreche/opssat-orbitai/issues/22#issuecomment-841690311). By way of example, consider the [Mochi folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi) which has the `MochiMochi @ ba8574e` gitsubmodule folder and the [test_data folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi/test_data) with the training and test datasets that we use to analyze the algorithm and models with custom code that we have in the [tools folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/Mochi/tools)

**Comment by georgeslabreche** [comment]
@TanguySoto I've unassigned @Evridiki-ase since she doesn't have capacity for the ranger related tasks anymore. As such I've removed all ranger related issues from the milestones until we've discussed how to include them (if possible) in our deliverable.

**Comment by georgeslabreche** [comment]
Housekeeping notes on leftover issues we need to look into when moving forward:

1. The ranger code was directly copy and pasted in the repo. A "git submodule" should be used instead. To prepare for this, I have forked the ranger repo and created an orbitai branch, here: https://github.com/georgeslabreche/ranger
2. I got clarification from @Evridiki-ase that I was looking at the wrong place for the `../training/mochi-2021-04-16_18-28-31/logs/` referred to in [the second point of this comment](https://github.com/georgeslabreche/opssat-orbitai/issues/22#issuecomment-849796013) and the path is from within [the cpp_version folder](https://github.com/georgeslabreche/opssat-orbitai/tree/3a28b663ff29f98b42ec9dc9e348a0c895ad0b4d/ranger/cpp_version). The file in question is [here](https://github.com/georgeslabreche/opssat-orbitai/blob/main/ranger/cpp_version/training/mochi-2021-04-18_02-51-48/logs/training_ranger.csv).
3. Although save/load has been documented, we need to create test data and run predictions on it in order to complete the validation of the ranger library. See [point 1 of this comment](https://github.com/georgeslabreche/opssat-orbitai/issues/22#issuecomment-849796013).
4. It's not clear yet if procedure 3 in the "Verifying the save and load functionalities" section of this issue's description is relevant to Random Forest or not. TBD.

**Comment by georgeslabreche** [comment]
Need to implement prediction for a given data sample rather than just batch predictions from reading a CSV file. Suggested command parameters:

```bash
./OrbitAI_ranger --verbose --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --input 0.01,0,1.12,0.29,0,0.02,1 --predict ranger_out.forest
./OrbitAI_ranger --verbose --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --input 0.01,0,0.28,0.2,0.01,1.16,0 --predict ranger_out.forest
```

Reduced initial scope of work in favor of implementing this requirement.
